{
    "url": "https://api.github.com/repos/jax-ml/jax/issues/26128",
    "repository_url": "https://api.github.com/repos/jax-ml/jax",
    "labels_url": "https://api.github.com/repos/jax-ml/jax/issues/26128/labels{/name}",
    "comments_url": "https://api.github.com/repos/jax-ml/jax/issues/26128/comments",
    "events_url": "https://api.github.com/repos/jax-ml/jax/issues/26128/events",
    "html_url": "https://github.com/jax-ml/jax/pull/26128",
    "id": 2813774182,
    "node_id": "PR_kwDOCTkjjc6JIBVQ",
    "number": 26128,
    "title": "jnp.linalg.norm: better documentation & error text for axis",
    "user": {
      "login": "jakevdp",
      "id": 781659,
      "node_id": "MDQ6VXNlcjc4MTY1OQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/781659?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakevdp",
      "html_url": "https://github.com/jakevdp",
      "followers_url": "https://api.github.com/users/jakevdp/followers",
      "following_url": "https://api.github.com/users/jakevdp/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakevdp/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakevdp/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakevdp/subscriptions",
      "organizations_url": "https://api.github.com/users/jakevdp/orgs",
      "repos_url": "https://api.github.com/users/jakevdp/repos",
      "events_url": "https://api.github.com/users/jakevdp/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakevdp/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 2356790151,
        "node_id": "MDU6TGFiZWwyMzU2NzkwMTUx",
        "url": "https://api.github.com/repos/jax-ml/jax/labels/pull%20ready",
        "name": "pull ready",
        "color": "d4c5f9",
        "default": false,
        "description": "Ready for copybara import and testing"
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": {
      "login": "jakevdp",
      "id": 781659,
      "node_id": "MDQ6VXNlcjc4MTY1OQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/781659?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakevdp",
      "html_url": "https://github.com/jakevdp",
      "followers_url": "https://api.github.com/users/jakevdp/followers",
      "following_url": "https://api.github.com/users/jakevdp/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakevdp/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakevdp/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakevdp/subscriptions",
      "organizations_url": "https://api.github.com/users/jakevdp/orgs",
      "repos_url": "https://api.github.com/users/jakevdp/repos",
      "events_url": "https://api.github.com/users/jakevdp/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakevdp/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "assignees": [
      {
        "login": "jakevdp",
        "id": 781659,
        "node_id": "MDQ6VXNlcjc4MTY1OQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/781659?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jakevdp",
        "html_url": "https://github.com/jakevdp",
        "followers_url": "https://api.github.com/users/jakevdp/followers",
        "following_url": "https://api.github.com/users/jakevdp/following{/other_user}",
        "gists_url": "https://api.github.com/users/jakevdp/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jakevdp/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jakevdp/subscriptions",
        "organizations_url": "https://api.github.com/users/jakevdp/orgs",
        "repos_url": "https://api.github.com/users/jakevdp/repos",
        "events_url": "https://api.github.com/users/jakevdp/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jakevdp/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
      }
    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2025-01-27T18:36:09Z",
    "updated_at": "2025-01-27T19:25:06Z",
    "closed_at": "2025-01-27T19:25:05Z",
    "author_association": "COLLABORATOR",
    "sub_issues_summary": {
      "total": 0,
      "completed": 0,
      "percent_completed": 0
    },
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/jax-ml/jax/pulls/26128",
      "html_url": "https://github.com/jax-ml/jax/pull/26128",
      "diff_url": "https://github.com/jax-ml/jax/pull/26128.diff",
      "patch_url": "https://github.com/jax-ml/jax/pull/26128.patch",
      "merged_at": "2025-01-27T19:25:05Z",
      "patch_url_body": "From a6a0226a53f26d5a17014fb1145050ffe1302bb4 Mon Sep 17 00:00:00 2001\nFrom: Jake VanderPlas <jakevdp@google.com>\nDate: Mon, 27 Jan 2025 10:39:19 -0800\nSubject: [PATCH] jnp.linalg.norm: better documentation & error text for axis\n\n---\n jax/_src/numpy/linalg.py | 10 +++++++---\n 1 file changed, 7 insertions(+), 3 deletions(-)\n\ndiff --git a/jax/_src/numpy/linalg.py b/jax/_src/numpy/linalg.py\nindex f3c10fd4eb90..9bbcd7b2a0e5 100644\n--- a/jax/_src/numpy/linalg.py\n+++ b/jax/_src/numpy/linalg.py\n@@ -1085,7 +1085,8 @@ def norm(x: ArrayLike, ord: int | str | None = None,\n     ord: specify the kind of norm to take. Default is Frobenius norm for matrices,\n       and the 2-norm for vectors. For other options, see Notes below.\n     axis: integer or sequence of integers specifying the axes over which the norm\n-      will be computed. Defaults to all axes of ``x``.\n+      will be computed. For a single axis, compute a vector norm. For two axes,\n+      compute a matrix norm. Defaults to all axes of ``x``.\n     keepdims: if True, the output array will have the same number of dimensions as\n       the input, with the size of reduced axes replaced by ``1`` (default: False).\n \n@@ -1113,6 +1114,9 @@ def norm(x: ArrayLike, ord: int | str | None = None,\n     - ``ord=2`` computes the 2-norm, i.e. the largest singular value\n     - ``ord=-2`` computes the smallest singular value\n \n+    In the special case of ``ord=None`` and ``axis=None``, this function accepts an\n+    array of any dimension and computes the vector 2-norm of the flattened array.\n+\n   Examples:\n     Vector norms:\n \n@@ -1201,8 +1205,8 @@ def norm(x: ArrayLike, ord: int | str | None = None,\n     else:\n       raise ValueError(f\"Invalid order '{ord}' for matrix norm.\")\n   else:\n-    raise ValueError(\n-        f\"Invalid axis values ({axis}) for jnp.linalg.norm.\")\n+    raise ValueError(f\"Improper number of axes for norm: {axis=}. Pass one axis to\"\n+                     \" compute a vector-norm, or two axes to compute a matrix-norm.\")\n \n @overload\n def qr(a: ArrayLike, mode: Literal[\"r\"]) -> Array: ...\n"
    },
    "body": "Fixes #26112",
    "closed_by": {
      "login": "copybara-service[bot]",
      "id": 56741989,
      "node_id": "MDM6Qm90NTY3NDE5ODk=",
      "avatar_url": "https://avatars.githubusercontent.com/in/44061?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/copybara-service%5Bbot%5D",
      "html_url": "https://github.com/apps/copybara-service",
      "followers_url": "https://api.github.com/users/copybara-service%5Bbot%5D/followers",
      "following_url": "https://api.github.com/users/copybara-service%5Bbot%5D/following{/other_user}",
      "gists_url": "https://api.github.com/users/copybara-service%5Bbot%5D/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/copybara-service%5Bbot%5D/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/copybara-service%5Bbot%5D/subscriptions",
      "organizations_url": "https://api.github.com/users/copybara-service%5Bbot%5D/orgs",
      "repos_url": "https://api.github.com/users/copybara-service%5Bbot%5D/repos",
      "events_url": "https://api.github.com/users/copybara-service%5Bbot%5D/events{/privacy}",
      "received_events_url": "https://api.github.com/users/copybara-service%5Bbot%5D/received_events",
      "type": "Bot",
      "user_view_type": "public",
      "site_admin": false
    },
    "reactions": {
      "url": "https://api.github.com/repos/jax-ml/jax/issues/26128/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/jax-ml/jax/issues/26128/timeline",
    "performed_via_github_app": null,
    "state_reason": null,
    "comments_url_body": [],
    "pull_request_url_body": {
      "url": "https://api.github.com/repos/jax-ml/jax/pulls/26128",
      "id": 2300581200,
      "node_id": "PR_kwDOCTkjjc6JIBVQ",
      "html_url": "https://github.com/jax-ml/jax/pull/26128",
      "diff_url": "https://github.com/jax-ml/jax/pull/26128.diff",
      "patch_url": "https://github.com/jax-ml/jax/pull/26128.patch",
      "issue_url": "https://api.github.com/repos/jax-ml/jax/issues/26128",
      "number": 26128,
      "state": "closed",
      "locked": false,
      "title": "jnp.linalg.norm: better documentation & error text for axis",
      "user": {
        "login": "jakevdp",
        "id": 781659,
        "node_id": "MDQ6VXNlcjc4MTY1OQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/781659?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jakevdp",
        "html_url": "https://github.com/jakevdp",
        "followers_url": "https://api.github.com/users/jakevdp/followers",
        "following_url": "https://api.github.com/users/jakevdp/following{/other_user}",
        "gists_url": "https://api.github.com/users/jakevdp/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jakevdp/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jakevdp/subscriptions",
        "organizations_url": "https://api.github.com/users/jakevdp/orgs",
        "repos_url": "https://api.github.com/users/jakevdp/repos",
        "events_url": "https://api.github.com/users/jakevdp/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jakevdp/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
      },
      "body": "Fixes #26112",
      "created_at": "2025-01-27T18:36:09Z",
      "updated_at": "2025-01-28T18:04:40Z",
      "closed_at": "2025-01-27T19:25:05Z",
      "merged_at": "2025-01-27T19:25:05Z",
      "merge_commit_sha": "763ffb3f73c2cdd4ebfe937c315c438412f847b0",
      "assignee": {
        "login": "jakevdp",
        "id": 781659,
        "node_id": "MDQ6VXNlcjc4MTY1OQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/781659?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jakevdp",
        "html_url": "https://github.com/jakevdp",
        "followers_url": "https://api.github.com/users/jakevdp/followers",
        "following_url": "https://api.github.com/users/jakevdp/following{/other_user}",
        "gists_url": "https://api.github.com/users/jakevdp/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jakevdp/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jakevdp/subscriptions",
        "organizations_url": "https://api.github.com/users/jakevdp/orgs",
        "repos_url": "https://api.github.com/users/jakevdp/repos",
        "events_url": "https://api.github.com/users/jakevdp/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jakevdp/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "jakevdp",
          "id": 781659,
          "node_id": "MDQ6VXNlcjc4MTY1OQ==",
          "avatar_url": "https://avatars.githubusercontent.com/u/781659?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/jakevdp",
          "html_url": "https://github.com/jakevdp",
          "followers_url": "https://api.github.com/users/jakevdp/followers",
          "following_url": "https://api.github.com/users/jakevdp/following{/other_user}",
          "gists_url": "https://api.github.com/users/jakevdp/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/jakevdp/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/jakevdp/subscriptions",
          "organizations_url": "https://api.github.com/users/jakevdp/orgs",
          "repos_url": "https://api.github.com/users/jakevdp/repos",
          "events_url": "https://api.github.com/users/jakevdp/events{/privacy}",
          "received_events_url": "https://api.github.com/users/jakevdp/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        }
      ],
      "requested_reviewers": [],
      "requested_teams": [],
      "labels": [
        {
          "id": 2356790151,
          "node_id": "MDU6TGFiZWwyMzU2NzkwMTUx",
          "url": "https://api.github.com/repos/jax-ml/jax/labels/pull%20ready",
          "name": "pull ready",
          "color": "d4c5f9",
          "default": false,
          "description": "Ready for copybara import and testing"
        }
      ],
      "milestone": null,
      "draft": false,
      "commits_url": "https://api.github.com/repos/jax-ml/jax/pulls/26128/commits",
      "review_comments_url": "https://api.github.com/repos/jax-ml/jax/pulls/26128/comments",
      "review_comment_url": "https://api.github.com/repos/jax-ml/jax/pulls/comments{/number}",
      "comments_url": "https://api.github.com/repos/jax-ml/jax/issues/26128/comments",
      "statuses_url": "https://api.github.com/repos/jax-ml/jax/statuses/a6a0226a53f26d5a17014fb1145050ffe1302bb4",
      "head": {
        "label": "jakevdp:norm-doc",
        "ref": "norm-doc",
        "sha": "a6a0226a53f26d5a17014fb1145050ffe1302bb4",
        "user": {
          "login": "jakevdp",
          "id": 781659,
          "node_id": "MDQ6VXNlcjc4MTY1OQ==",
          "avatar_url": "https://avatars.githubusercontent.com/u/781659?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/jakevdp",
          "html_url": "https://github.com/jakevdp",
          "followers_url": "https://api.github.com/users/jakevdp/followers",
          "following_url": "https://api.github.com/users/jakevdp/following{/other_user}",
          "gists_url": "https://api.github.com/users/jakevdp/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/jakevdp/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/jakevdp/subscriptions",
          "organizations_url": "https://api.github.com/users/jakevdp/orgs",
          "repos_url": "https://api.github.com/users/jakevdp/repos",
          "events_url": "https://api.github.com/users/jakevdp/events{/privacy}",
          "received_events_url": "https://api.github.com/users/jakevdp/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "repo": {
          "id": 253380559,
          "node_id": "MDEwOlJlcG9zaXRvcnkyNTMzODA1NTk=",
          "name": "jax",
          "full_name": "jakevdp/jax",
          "private": false,
          "owner": {
            "login": "jakevdp",
            "id": 781659,
            "node_id": "MDQ6VXNlcjc4MTY1OQ==",
            "avatar_url": "https://avatars.githubusercontent.com/u/781659?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/jakevdp",
            "html_url": "https://github.com/jakevdp",
            "followers_url": "https://api.github.com/users/jakevdp/followers",
            "following_url": "https://api.github.com/users/jakevdp/following{/other_user}",
            "gists_url": "https://api.github.com/users/jakevdp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/jakevdp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/jakevdp/subscriptions",
            "organizations_url": "https://api.github.com/users/jakevdp/orgs",
            "repos_url": "https://api.github.com/users/jakevdp/repos",
            "events_url": "https://api.github.com/users/jakevdp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/jakevdp/received_events",
            "type": "User",
            "user_view_type": "public",
            "site_admin": false
          },
          "html_url": "https://github.com/jakevdp/jax",
          "description": "Composable transformations of Python+NumPy programs: differentiate, vectorize, JIT to GPU/TPU, and more",
          "fork": true,
          "url": "https://api.github.com/repos/jakevdp/jax",
          "forks_url": "https://api.github.com/repos/jakevdp/jax/forks",
          "keys_url": "https://api.github.com/repos/jakevdp/jax/keys{/key_id}",
          "collaborators_url": "https://api.github.com/repos/jakevdp/jax/collaborators{/collaborator}",
          "teams_url": "https://api.github.com/repos/jakevdp/jax/teams",
          "hooks_url": "https://api.github.com/repos/jakevdp/jax/hooks",
          "issue_events_url": "https://api.github.com/repos/jakevdp/jax/issues/events{/number}",
          "events_url": "https://api.github.com/repos/jakevdp/jax/events",
          "assignees_url": "https://api.github.com/repos/jakevdp/jax/assignees{/user}",
          "branches_url": "https://api.github.com/repos/jakevdp/jax/branches{/branch}",
          "tags_url": "https://api.github.com/repos/jakevdp/jax/tags",
          "blobs_url": "https://api.github.com/repos/jakevdp/jax/git/blobs{/sha}",
          "git_tags_url": "https://api.github.com/repos/jakevdp/jax/git/tags{/sha}",
          "git_refs_url": "https://api.github.com/repos/jakevdp/jax/git/refs{/sha}",
          "trees_url": "https://api.github.com/repos/jakevdp/jax/git/trees{/sha}",
          "statuses_url": "https://api.github.com/repos/jakevdp/jax/statuses/{sha}",
          "languages_url": "https://api.github.com/repos/jakevdp/jax/languages",
          "stargazers_url": "https://api.github.com/repos/jakevdp/jax/stargazers",
          "contributors_url": "https://api.github.com/repos/jakevdp/jax/contributors",
          "subscribers_url": "https://api.github.com/repos/jakevdp/jax/subscribers",
          "subscription_url": "https://api.github.com/repos/jakevdp/jax/subscription",
          "commits_url": "https://api.github.com/repos/jakevdp/jax/commits{/sha}",
          "git_commits_url": "https://api.github.com/repos/jakevdp/jax/git/commits{/sha}",
          "comments_url": "https://api.github.com/repos/jakevdp/jax/comments{/number}",
          "issue_comment_url": "https://api.github.com/repos/jakevdp/jax/issues/comments{/number}",
          "contents_url": "https://api.github.com/repos/jakevdp/jax/contents/{+path}",
          "compare_url": "https://api.github.com/repos/jakevdp/jax/compare/{base}...{head}",
          "merges_url": "https://api.github.com/repos/jakevdp/jax/merges",
          "archive_url": "https://api.github.com/repos/jakevdp/jax/{archive_format}{/ref}",
          "downloads_url": "https://api.github.com/repos/jakevdp/jax/downloads",
          "issues_url": "https://api.github.com/repos/jakevdp/jax/issues{/number}",
          "pulls_url": "https://api.github.com/repos/jakevdp/jax/pulls{/number}",
          "milestones_url": "https://api.github.com/repos/jakevdp/jax/milestones{/number}",
          "notifications_url": "https://api.github.com/repos/jakevdp/jax/notifications{?since,all,participating}",
          "labels_url": "https://api.github.com/repos/jakevdp/jax/labels{/name}",
          "releases_url": "https://api.github.com/repos/jakevdp/jax/releases{/id}",
          "deployments_url": "https://api.github.com/repos/jakevdp/jax/deployments",
          "created_at": "2020-04-06T02:55:00Z",
          "updated_at": "2024-09-19T22:29:04Z",
          "pushed_at": "2025-02-14T22:17:38Z",
          "git_url": "git://github.com/jakevdp/jax.git",
          "ssh_url": "git@github.com:jakevdp/jax.git",
          "clone_url": "https://github.com/jakevdp/jax.git",
          "svn_url": "https://github.com/jakevdp/jax",
          "homepage": "",
          "size": 105773,
          "stargazers_count": 8,
          "watchers_count": 8,
          "language": "Python",
          "has_issues": false,
          "has_projects": true,
          "has_downloads": true,
          "has_wiki": true,
          "has_pages": false,
          "has_discussions": false,
          "forks_count": 2,
          "mirror_url": null,
          "archived": false,
          "disabled": false,
          "open_issues_count": 0,
          "license": {
            "key": "apache-2.0",
            "name": "Apache License 2.0",
            "spdx_id": "Apache-2.0",
            "url": "https://api.github.com/licenses/apache-2.0",
            "node_id": "MDc6TGljZW5zZTI="
          },
          "allow_forking": true,
          "is_template": false,
          "web_commit_signoff_required": false,
          "topics": [],
          "visibility": "public",
          "forks": 2,
          "open_issues": 0,
          "watchers": 8,
          "default_branch": "master"
        }
      },
      "base": {
        "label": "jax-ml:main",
        "ref": "main",
        "sha": "e57f3112e0135e06cd68bda84187af169389d445",
        "user": {
          "login": "jax-ml",
          "id": 58486408,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjU4NDg2NDA4",
          "avatar_url": "https://avatars.githubusercontent.com/u/58486408?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/jax-ml",
          "html_url": "https://github.com/jax-ml",
          "followers_url": "https://api.github.com/users/jax-ml/followers",
          "following_url": "https://api.github.com/users/jax-ml/following{/other_user}",
          "gists_url": "https://api.github.com/users/jax-ml/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/jax-ml/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/jax-ml/subscriptions",
          "organizations_url": "https://api.github.com/users/jax-ml/orgs",
          "repos_url": "https://api.github.com/users/jax-ml/repos",
          "events_url": "https://api.github.com/users/jax-ml/events{/privacy}",
          "received_events_url": "https://api.github.com/users/jax-ml/received_events",
          "type": "Organization",
          "user_view_type": "public",
          "site_admin": false
        },
        "repo": {
          "id": 154739597,
          "node_id": "MDEwOlJlcG9zaXRvcnkxNTQ3Mzk1OTc=",
          "name": "jax",
          "full_name": "jax-ml/jax",
          "private": false,
          "owner": {
            "login": "jax-ml",
            "id": 58486408,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjU4NDg2NDA4",
            "avatar_url": "https://avatars.githubusercontent.com/u/58486408?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/jax-ml",
            "html_url": "https://github.com/jax-ml",
            "followers_url": "https://api.github.com/users/jax-ml/followers",
            "following_url": "https://api.github.com/users/jax-ml/following{/other_user}",
            "gists_url": "https://api.github.com/users/jax-ml/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/jax-ml/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/jax-ml/subscriptions",
            "organizations_url": "https://api.github.com/users/jax-ml/orgs",
            "repos_url": "https://api.github.com/users/jax-ml/repos",
            "events_url": "https://api.github.com/users/jax-ml/events{/privacy}",
            "received_events_url": "https://api.github.com/users/jax-ml/received_events",
            "type": "Organization",
            "user_view_type": "public",
            "site_admin": false
          },
          "html_url": "https://github.com/jax-ml/jax",
          "description": "Composable transformations of Python+NumPy programs: differentiate, vectorize, JIT to GPU/TPU, and more",
          "fork": false,
          "url": "https://api.github.com/repos/jax-ml/jax",
          "forks_url": "https://api.github.com/repos/jax-ml/jax/forks",
          "keys_url": "https://api.github.com/repos/jax-ml/jax/keys{/key_id}",
          "collaborators_url": "https://api.github.com/repos/jax-ml/jax/collaborators{/collaborator}",
          "teams_url": "https://api.github.com/repos/jax-ml/jax/teams",
          "hooks_url": "https://api.github.com/repos/jax-ml/jax/hooks",
          "issue_events_url": "https://api.github.com/repos/jax-ml/jax/issues/events{/number}",
          "events_url": "https://api.github.com/repos/jax-ml/jax/events",
          "assignees_url": "https://api.github.com/repos/jax-ml/jax/assignees{/user}",
          "branches_url": "https://api.github.com/repos/jax-ml/jax/branches{/branch}",
          "tags_url": "https://api.github.com/repos/jax-ml/jax/tags",
          "blobs_url": "https://api.github.com/repos/jax-ml/jax/git/blobs{/sha}",
          "git_tags_url": "https://api.github.com/repos/jax-ml/jax/git/tags{/sha}",
          "git_refs_url": "https://api.github.com/repos/jax-ml/jax/git/refs{/sha}",
          "trees_url": "https://api.github.com/repos/jax-ml/jax/git/trees{/sha}",
          "statuses_url": "https://api.github.com/repos/jax-ml/jax/statuses/{sha}",
          "languages_url": "https://api.github.com/repos/jax-ml/jax/languages",
          "stargazers_url": "https://api.github.com/repos/jax-ml/jax/stargazers",
          "contributors_url": "https://api.github.com/repos/jax-ml/jax/contributors",
          "subscribers_url": "https://api.github.com/repos/jax-ml/jax/subscribers",
          "subscription_url": "https://api.github.com/repos/jax-ml/jax/subscription",
          "commits_url": "https://api.github.com/repos/jax-ml/jax/commits{/sha}",
          "git_commits_url": "https://api.github.com/repos/jax-ml/jax/git/commits{/sha}",
          "comments_url": "https://api.github.com/repos/jax-ml/jax/comments{/number}",
          "issue_comment_url": "https://api.github.com/repos/jax-ml/jax/issues/comments{/number}",
          "contents_url": "https://api.github.com/repos/jax-ml/jax/contents/{+path}",
          "compare_url": "https://api.github.com/repos/jax-ml/jax/compare/{base}...{head}",
          "merges_url": "https://api.github.com/repos/jax-ml/jax/merges",
          "archive_url": "https://api.github.com/repos/jax-ml/jax/{archive_format}{/ref}",
          "downloads_url": "https://api.github.com/repos/jax-ml/jax/downloads",
          "issues_url": "https://api.github.com/repos/jax-ml/jax/issues{/number}",
          "pulls_url": "https://api.github.com/repos/jax-ml/jax/pulls{/number}",
          "milestones_url": "https://api.github.com/repos/jax-ml/jax/milestones{/number}",
          "notifications_url": "https://api.github.com/repos/jax-ml/jax/notifications{?since,all,participating}",
          "labels_url": "https://api.github.com/repos/jax-ml/jax/labels{/name}",
          "releases_url": "https://api.github.com/repos/jax-ml/jax/releases{/id}",
          "deployments_url": "https://api.github.com/repos/jax-ml/jax/deployments",
          "created_at": "2018-10-25T21:25:02Z",
          "updated_at": "2025-02-17T17:00:51Z",
          "pushed_at": "2025-02-17T16:54:33Z",
          "git_url": "git://github.com/jax-ml/jax.git",
          "ssh_url": "git@github.com:jax-ml/jax.git",
          "clone_url": "https://github.com/jax-ml/jax.git",
          "svn_url": "https://github.com/jax-ml/jax",
          "homepage": "http://jax.readthedocs.io/",
          "size": 107371,
          "stargazers_count": 31295,
          "watchers_count": 31295,
          "language": "Python",
          "has_issues": true,
          "has_projects": false,
          "has_downloads": true,
          "has_wiki": false,
          "has_pages": false,
          "has_discussions": true,
          "forks_count": 2889,
          "mirror_url": null,
          "archived": false,
          "disabled": false,
          "open_issues_count": 1910,
          "license": {
            "key": "apache-2.0",
            "name": "Apache License 2.0",
            "spdx_id": "Apache-2.0",
            "url": "https://api.github.com/licenses/apache-2.0",
            "node_id": "MDc6TGljZW5zZTI="
          },
          "allow_forking": true,
          "is_template": false,
          "web_commit_signoff_required": false,
          "topics": [
            "jax"
          ],
          "visibility": "public",
          "forks": 2889,
          "open_issues": 1910,
          "watchers": 31295,
          "default_branch": "main"
        }
      },
      "_links": {
        "self": {
          "href": "https://api.github.com/repos/jax-ml/jax/pulls/26128"
        },
        "html": {
          "href": "https://github.com/jax-ml/jax/pull/26128"
        },
        "issue": {
          "href": "https://api.github.com/repos/jax-ml/jax/issues/26128"
        },
        "comments": {
          "href": "https://api.github.com/repos/jax-ml/jax/issues/26128/comments"
        },
        "review_comments": {
          "href": "https://api.github.com/repos/jax-ml/jax/pulls/26128/comments"
        },
        "review_comment": {
          "href": "https://api.github.com/repos/jax-ml/jax/pulls/comments{/number}"
        },
        "commits": {
          "href": "https://api.github.com/repos/jax-ml/jax/pulls/26128/commits"
        },
        "statuses": {
          "href": "https://api.github.com/repos/jax-ml/jax/statuses/a6a0226a53f26d5a17014fb1145050ffe1302bb4"
        }
      },
      "author_association": "COLLABORATOR",
      "auto_merge": null,
      "active_lock_reason": null,
      "merged": true,
      "mergeable": null,
      "rebaseable": null,
      "mergeable_state": "unknown",
      "merged_by": {
        "login": "copybara-service[bot]",
        "id": 56741989,
        "node_id": "MDM6Qm90NTY3NDE5ODk=",
        "avatar_url": "https://avatars.githubusercontent.com/in/44061?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/copybara-service%5Bbot%5D",
        "html_url": "https://github.com/apps/copybara-service",
        "followers_url": "https://api.github.com/users/copybara-service%5Bbot%5D/followers",
        "following_url": "https://api.github.com/users/copybara-service%5Bbot%5D/following{/other_user}",
        "gists_url": "https://api.github.com/users/copybara-service%5Bbot%5D/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/copybara-service%5Bbot%5D/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/copybara-service%5Bbot%5D/subscriptions",
        "organizations_url": "https://api.github.com/users/copybara-service%5Bbot%5D/orgs",
        "repos_url": "https://api.github.com/users/copybara-service%5Bbot%5D/repos",
        "events_url": "https://api.github.com/users/copybara-service%5Bbot%5D/events{/privacy}",
        "received_events_url": "https://api.github.com/users/copybara-service%5Bbot%5D/received_events",
        "type": "Bot",
        "user_view_type": "public",
        "site_admin": false
      },
      "comments": 0,
      "review_comments": 0,
      "maintainer_can_modify": false,
      "commits": 1,
      "additions": 7,
      "deletions": 3,
      "changed_files": 1,
      "review_comments_url_body": []
    }
  }